' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.

' Preview durch <Alt>d

@startuml Controller-Klasse

interface Promise<T>

package @nestjs/common {
  class "@Controller" as Controller
  hide Controller circle

  class "@UseGuards" as UseGuards
  hide UseGuards circle

  class "@UseInterceptors" as UseInterceptors
  hide UseInterceptors circle

  class "@Post" as Post
  hide Post circle

  class "@Put" as Put
  hide Put circle

  class "@Patch" as Patch
  hide Patch circle

  class "@Req" as Req
  hide Req circle

  class "@Res" as Res
  hide Res circle

  class "@Param" as Param
  hide Param circle

  class "@Body" as Body
  hide Body circle

  class "@Headers" as Headers
  hide Headers circle

  UseInterceptors .[hidden].> Post
  UseInterceptors .[hidden].> Put
  UseInterceptors .[hidden].> Patch

  Post .[hidden].> Req
  Post .[hidden].> Res
  Post .[hidden].> Param
  Post .[hidden].> Body
  Post .[hidden].> Headers
}

package nest-keycloak-connect {
  class AuthGuard

  class "@Roles" as Roles
  hide Roles circle
}

package express {
  class Request
  class Response

  Response .right[hidden].> Controller
}

package bike {
  package entity #FFFFFF {
    class Bike <<entity>>

    Bike .[hidden].> Promise
    Bike .[hidden].> Request
  }

  package service {
    class BikeWriteService << control >>
    class MailService
  }

  package rest #DDDDDD {
    class BikeWriteController << control >> << @Controller() >> << @UseGuards() >> << @UseInterceptors() >> {
      + @Post() @Roles() async writeBike(@Body() bike: Bike, @Req() req: Request,  @Res() res: Response): Promise<Response>
      + @Put() @Roles() async updateBike(@Body() bike: Bike, @Param() id: number, @Headers() version: string, @Res() res: Response): Promise<Response>
      + @Patch() @Roles() async updateBikePrice(@Param() id: number, @Body() price: number, @Res() res: Response): Promise<Response>
    }

    BikeWriteController o--> "1" BikeWriteService : service
    BikeWriteController ..up> Bike

    BikeWriteController ..> Controller

    BikeWriteController .up.> AuthGuard
    BikeWriteController .up.> Roles

    BikeWriteController ..> Request
    BikeWriteController ..> Response
    BikeWriteController ..> Promise

    Bike .up[hidden].> Roles
    BikeWriteService o--> MailService : mailService
    BikeWriteService .[hidden].> Promise
  }
}

hide empty members

footer (c) Gruppe 7

@enduml
