' Copyright (C) 2025 - present [Dein Name oder Hochschule]
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.

' Preview durch <Alt>d

@startuml Anwendungskern

interface Promise<T>

package @nestjs/common {
  class "@Injectable" as Injectable
  hide Injectable circle
}

package typeorm {
  class Repository<T>
}

package @nestjs/typeorm {
  class "@InjectRepository" as InjectRepository
  hide InjectRepository circle
}

package mail {
  class MailService
}

package bike {
  package entity {
    class Bike
  }

  package service #DDDDDD {
    class BikeWriteService << control >> <<@Injectable()>> {
      + async createBike(bikeData: Partial<Bike>): Promise<Bike>
      + async updateBike(id: number, bikeData: Partial<Bike>): Promise<Bike>
      + async updateBikePrice(id: number, price: number): Promise<Bike>
    }

    BikeWriteService o--> "1" Repository : @InjectRepository bikeRepository
    BikeWriteService o--> "1" MailService : mailService

    BikeWriteService .up.> Injectable
    BikeWriteService .up.> InjectRepository

    BikeWriteService .up.> Promise
    BikeWriteService ..> Bike

    MailService .[hidden].> Promise
    Bike .[hidden].> Promise
  }
}

hide empty members

footer (c) Gruppe 7

@enduml
