' Copyright (C) 2025 - present [Dein Name oder Hochschule]
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.

' Preview durch <Alt>d

@startuml ER Diagramm

hide circle
skinparam linetype ortho

entity "Bike" {
  * id: integer <<generated>>
  --
  * brand: text
  * type: text
  * frameSize: text
  * price: number
  * available: boolean
}

entity "BikeTitle" {
  * bikeId: integer <<PK, FK>>
  --
  * title: text
  * subtitle: text
}

Bike ||--|| BikeTitle

footer (c) Gruppe 7

@enduml
