name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Ensure acme-network exists
        run: docker network create acme-network || true

      - name: Start backend services
        run: docker compose -f .extras/compose/debug/compose.yml up -d

      - name: Wait for backend to be ready
        run: sleep 15

      - name: Test
        run: npm test -- --coverage --runInBand

      - name: Stop backend services
        if: always()
        run: docker compose -f .extras/compose/debug/compose.yml down

      - name: Lint source
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Security Audit
        run: npm audit --omit=dev || true

      - name: Generate AsciiDoc Docs
        run: npm run asciidoctor

      - name: Generate reveal.js Slides
        run: npm run revealjs

      - name: Generate API Docs
        run: npm run typedoc

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage

      - name: Upload generated docs
        uses: actions/upload-artifact@v4
        with:
          name: bike-docs
          path: |
            .extras/doc/projekthandbuch/html
            .extras/doc/folien
            .extras/doc/api
